[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
reruns = 3
rerunsDelay = 2

addopts =
    -v
    --strict-markers
    --tb=short
    --disable-warnings
    --alluredir=allure_results
